const BASE_URL = "http://localhost:3000"

const USER_BASE_ENDPOINT = `${BASE_URL}/user`

const ACTIVITY_ENDPOINT = "/activity"
const SESSION_AVERAGE_ENDPOINT = "/average-sessions"
const PERFORMANCE_ENDPOINT = "/performance"

const MOCK_USER_ID = "12"

const CHART_SIZE = 280

export {
  MOCK_USER_ID,
  BASE_URL,
  USER_BASE_ENDPOINT,
  ACTIVITY_ENDPOINT,
  SESSION_AVERAGE_ENDPOINT,
  PERFORMANCE_ENDPOINT,
  CHART_SIZE,
}
